# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GlovoCodeChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GlovoCodeChallenge
  pod 'RxDataSources'
  pod 'RxSwift',  '~> 4.4.2'
  pod 'RxCocoa',  '~> 4.4.2'
  pod 'Moya/RxSwift', '~> 12.0.1'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SnapKit', '~> 4.0.0'

  target 'GlovoCodeChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GlovoCodeChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
